# Generated by Django 5.1.7 on 2025-03-10 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_remove_userprofile_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_status',
        ),
    ]
