# Generated by Django 5.1.7 on 2025-03-10 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_userprofile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_image',
            new_name='profile_picture',
        ),
    ]
